xiphonics/picoTracker

sources/Application/Instruments/SampleInstrument.cpp
sources/Application/Instruments/SampleInstrument.h
sources/Application/Instruments/SampleInstrumentDatas.h

This was my attempt at creating a pingpong loop mode in LGPT
Unfortunately I'm not great with direct pointer access as I'm more of an OOP person myself so it does trigger occasional segfaults.
Most often these segfaults happen when the full length of the sound file has passed and is turning around, especially in conjunction with looping back to the start of the song

Pingpong patch

---

sources/Application/Instruments/SamplePool.cpp
sources/Application/Instruments/SamplePool.h
sources/Application/Instruments/WavFile.cpp
sources/Application/Instruments/WavFile.h

Autodetect flash size at the time sample pool is initialized.

Autodetect flash size, fixes #18

---

sources/Application/Utils/HelpLegend.h
sources/Application/Views/PhraseView.cpp
sources/Application/Views/TableView.cpp

*Overwrite old text with spaces
*Nicer line breaks
*Corrected / added missing commands

Make help legend less busy

---

sources/Application/Instruments/SamplePool.cpp
sources/Application/Model/Project.cpp

Added missing loading sample call for project laod as was removed when adding faster import message, along with some comments to help me understand  the import and load flows. Also added a saving project message so you know it's saving. This can be removed when autosaving so it doesn't distract

Adds back "Loading" sample status when loading a project. Also shows saving a project status when you do so.

---

sources/Application/Instruments/I_Instrument.h
sources/Application/Instruments/InstrumentBank.cpp
sources/Application/Instruments/MidiInstrument.cpp
sources/Application/Instruments/MidiInstrument.h
sources/Application/Instruments/SampleInstrument.cpp
sources/Application/Instruments/SampleInstrument.h
sources/Application/Model/Config.cpp
sources/Application/Model/Project.cpp
sources/Application/Views/BaseClasses/UIField.h
sources/Application/Views/BaseClasses/UIIntVarField.cpp
sources/Application/Views/PhraseView.cpp
sources/Foundation/Variables/Variable.cpp
sources/Foundation/Variables/Variable.h

Haven't tested config. Rest of things seem to work fine, but haven't tested thoroughly. Most of this is pretty low hanging fruit, there's probably a lot more.

savings of 25kb+ #139

---

sources/Application/Views/InstrumentView.cpp
sources/CMakeLists.txt

Didn't really understand how to emplace values. This way it creates the values "in place" on the vector without using stack space.

emplace done right, duh!

---

sources/Application/Instruments/InstrumentBank.cpp

Removes delete of next available slot and just reassigns it. 
Fixes: #176

Fix clone instrument 

---

sources/Application/Views/ImportView.cpp
sources/Application/Views/ImportView.h
sources/Application/Views/InstrumentView.cpp

use new sample dir path everywhere

---

sources/Application/Views/DeviceView.cpp

Need to use addlistener for field changes so that they are persisted when their values are changed.
Fixes: #228

Listeners need so that remoteui & font persisted

---

sources/Application/Views/InstrumentView.cpp

Show error dialog when preventing instrument type change during playback

---

usermanual/content/pages/chains.md
usermanual/content/pages/getting-started.md
usermanual/content/pages/grooves.md
usermanual/content/pages/instruments.md
usermanual/content/pages/introduction.md
usermanual/content/pages/keypadcombos.md
usermanual/content/pages/phrases.md
usermanual/content/pages/scales.md
usermanual/content/pages/songs.md

* Update names of keys using consistent formatting
* Update introduction

User Manual updates

---

usermanual/content/pages/chains.md
usermanual/content/pages/device.md
usermanual/content/pages/getting-started.md
usermanual/content/pages/grooves.md
usermanual/content/pages/instruments.md
usermanual/content/pages/keypadcombos.md
usermanual/content/pages/phrases.md
usermanual/content/pages/projects.md
usermanual/content/pages/songs.md
usermanual/content/pages/tables.md

Make all image urls relative

---

sources/Application/Views/SelectProjectView.cpp

Don't show the "untitled" project entry

---

usermanual/content/pages/getting-started.md

Add keymap naming to getting started chapter

---

sources/Adapters/picoTracker/usb/usb_descriptors.c

Also switch to use standard RPI rp2040 USB VID/PID.
Fixes: #281

Fix conflict in CDC & MIDI endpoints

---

sources/Application/Views/ImportView.cpp

Reset scroll offset when entering new directory

---

sources/System/FileSystem/CMakeLists.txt
sources/System/FileSystem/PicoFileSystem.cpp
sources/System/FileSystem/PicoFileSystem.h

Protect sdcard access from races across both cores

---

sources/Application/Instruments/InstrumentBank.cpp
sources/Application/Instruments/InstrumentBank.h
sources/Application/Instruments/SIDInstrument.cpp
sources/Application/Instruments/SIDInstrument.h
sources/Application/Views/InstrumentView.cpp
sources/Application/Views/InstrumentView.h
sources/Externals/cRSID/SID.cpp
sources/Externals/cRSID/SID.h
sources/Foundation/Types/Types.h

Fixes SID UI to allow selecting the oscillator for each SIDInstrument, improvements to the SIDInstruments UI on the instrument screen and some modest performance improvement to rendering by removing function calls from the sample rendering hot loop.

Initial SID fixes

---

sources/Application/Instruments/SampleInstrument.cpp
sources/Application/Model/Project.cpp
sources/Application/Views/ProjectView.cpp

Also includes some minimal code cleanup.
Fixes: #20

Only attempt to purge sample instruments

---

sources/Application/Views/BaseClasses/UIField.h
sources/Application/Views/BaseClasses/UITextField.cpp
sources/Application/Views/BaseClasses/UITextField.h

Fix delete key in project name field

---

sources/Application/Model/Config.cpp

Make remote ui on by default

---

sources/Adapters/picoTracker/gui/picoTrackerGUIWindowImp.cpp
usermanual/content/pages/appendix-remoteui.md

Send remoteui protocol colors as RGB888 not 565

---

sources/Application/Instruments/InstrumentBank.cpp
sources/Application/Instruments/InstrumentBank.h
sources/Application/Views/PhraseView.cpp

Choose next avail instr slot for each new instr

---

sources/Adapters/picoTracker/gui/SerialDebugUI.cpp
sources/Adapters/picoTracker/gui/SerialDebugUI.h
sources/Application/Persistency/PersistencyService.cpp
sources/System/FileSystem/PicoFileSystem.cpp
sources/System/FileSystem/PicoFileSystem.h

Also adds mkdir cmd to serial debug repl to test mkdir function.
Fixes: #360

fix creating sample dir in when project save-as

---

usermanual/content/pages/chains.md
usermanual/content/pages/phrases.md
usermanual/content/pages/songs.md

update docs for song screen controls & play modes

---

sources/Application/Audio/AudioFileStreamer.cpp
sources/Application/Audio/AudioFileStreamer.h
sources/Application/Audio/CMakeLists.txt
sources/Application/Player/PlayerMixer.cpp
sources/Services/Audio/AudioMixer.cpp

Also removes unused legacy config "preattentuation" setting.
Fixes: #335

Use master volume setting for preview sample playback 

---

sources/Application/Views/DeviceView.cpp

*sigh*, just a silly, off by 1 typo.
Fixes: #375

Fix possible ui values for remoteUI setting

---

sources/Application/Views/ImportView.cpp

Prevent importing sample while previewing sample

---

usermanual/content/pages/instruments.md
usermanual/content/pages/phrases.md

Also made improvements to SID, sampler and MIDI instrument documentation.
Fixes: #300, #372

Document instrument perf limits and nav keycombo

---

sources/Application/Instruments/InstrumentBank.cpp

Followup to fix #368 correctly as prev fix still had bug when first instrument mapping would not be saved.

Fix incrementing instrument index correctly

---

sources/Application/Instruments/MidiInstrument.cpp
sources/Application/Model/Scale.cpp
sources/Application/Model/Scale.h
sources/Application/Player/Player.h

Apply current scale to midi chord cmd offset values

---

sources/Application/Instruments/MidiInstrument.cpp
sources/Application/Instruments/MidiInstrument.h
sources/Services/Midi/MidiMessage.h

This is a new commit without the merge that breaks the previous pull request https://github.com/xiphonics/picoTracker/pull/451
Apologies for the mess!
Fixes: #448

MIDI instrument volume (replaces pr 451)

---

usermanual/content/includes/sidepanel
usermanual/content/pages/instruments.md

User manual only, no code changes.
Fixes: #244

Improve instruments chapter, add tips to nav panel

---

sources/Application/Model/Project.cpp
sources/Application/Views/SongView.cpp
sources/Application/Views/SongView.h
usermanual/content/pages/songs.md

This code was originally contributed by @djdiskmachine in #216.
Fixes: #478

Enable and document tempo nudge

---

sources/Application/Views/ImportView.cpp
sources/Application/Views/ImportView.h
usermanual/content/pages/instruments.md

Remove restriction of browsing outside /samples

---

.github/workflows/ghpages-hosting-merge.yml
usermanual/content/pages/instruments.md

Also limits user manual deploys to only happen from the release branch.
Fixes: #493 #498

Usermanual: highlight multisample import workflow

---

sources/Application/Persistency/PersistencyService.cpp

Add firmware version number to instrument exports

---

usermanual/content/pages/device.md
usermanual/content/pages/instruments.md
usermanual/content/pages/mixer.md
usermanual/content/pages/theme.md
usermanual/content/pages/tipstricks.md

Remove refs to v2.1 from user manual

---

sources/Application/Views/ProjectView.cpp

Don't prevent project save while sequencer running

---

sources/Application/Views/InstrumentView.cpp

This makes the open import sample browser subscreen field key combo consistent with the project load, instrument and theme import "button" fields.
Fixes: #459

Single ENTER to open import sample subscreen

---

sources/Application/Views/TableView.cpp
sources/Application/Views/TableView.h

Fix table overscroll by using correct unsigned int

---

sources/Application/Instruments/SamplePool.cpp
sources/Application/Instruments/WavFile.cpp

Displaying overall & loading into flash progress

---

sources/Foundation/Types/Types.h

Fix scaleroot name param in project data

---

sources/Application/Instruments/I_Instrument.cpp
sources/Application/Persistency/PersistencyService.cpp
sources/Application/Views/BaseClasses/View.h
sources/Application/Views/InstrumentImportView.cpp
sources/Application/Views/InstrumentView.cpp
sources/Application/Views/InstrumentView.h

Apart from fixing the previous breakage in event handling for the instrument type field and checking for instrument settings having been modified, also refactored that code to make it simpler and changed from using static function to lambda to remove need for extra class fields.
Fixes: #552

Fix instrument change check

---

sources/Application/Instruments/SampleInstrument.cpp
sources/Application/Views/InstrumentView.cpp

Not sure how this regression happened, the functionality seems to have got lost amid the changes and merges that happened in this part of the code recently.
Fixes: #567

Instrument screen fields not updating

---

sources/Application/Views/TableView.cpp
sources/Application/Views/TableView.h

For now there is not enough space for the vumeter on table screen.
Fixes: #576

Remove vu meter from table screen

---

sources/Adapters/picoTracker/midi/picoTrackerUSBMidiInDevice.cpp

Fix USB MIDI in data handling based on CIN

---

sources/Application/Audio/AudioFileStreamer.cpp
sources/Application/Views/ImportView.cpp

Also remove duplicte unused code.
Partially fixes #596

Detect AKWF "nes" pack singlecycle samples

---

sources/Application/Model/Config.cpp

Fix accidental double up in config params list

---

sources/Adapters/picoTracker/platform/platform.cpp
sources/Adapters/picoTracker/platform/platform.h
sources/Adapters/picoTracker/system/picoTrackerSystem.cpp
sources/Adapters/picoTracker/system/picoTrackerSystem.h
sources/Application/Model/Config.cpp
sources/Application/Views/DeviceView.cpp
sources/Application/Views/DeviceView.h
sources/CMakeLists.txt
sources/Foundation/Types/Types.h
sources/System/System/System.h
usermanual/content/pages/device.md

This adds setting for display backlight level for v2 and newer PCBs.
Fixes: #640

Display brightness

---

sources/Application/Instruments/SamplePool.h
sources/Application/Views/ImportView.cpp

Also increases max sample files limit per project from 16 to 64.
Fixes: #628

Show error dialog when projects max samples reached

---

sources/Application/Views/ChainView.cpp
sources/Application/Views/PhraseView.cpp
sources/Application/Views/SongView.cpp

Ensure vu meter always redrawn, also fix VU meter position on phrase screen

---

sources/Adapters/picoTracker/system/picoTrackerSystem.cpp
sources/Adapters/picoTracker/system/picoTrackerSystem.h
sources/Application/Views/BaseClasses/View.cpp
sources/Application/Views/BaseClasses/View.h
sources/CMakeLists.txt
sources/System/System/System.h

Detailed battery state

---

sources/Application/Instruments/SamplePool.cpp
sources/Application/Views/InstrumentImportView.cpp

Check for filenames that are too long on project load

---

sources/Adapters/picoTracker/system/picoTrackerSamplePool.h
sources/Application/Instruments/SamplePool.h
sources/Application/Views/ImportView.cpp

UI must *not* depend directly on adapter code

GetAvailableSampleStorageSpace() on interface

---

sources/Application/Persistency/PersistencyDocument.cpp
sources/Application/Persistency/PersistencyDocument.h

Close project files after reading

---

sources/Adapters/picoTracker/gui/picoRemoteUI.cpp
sources/Adapters/picoTracker/gui/picoRemoteUI.h
sources/Adapters/picoTracker/gui/picoTrackerGUIWindowImp.cpp
usermanual/content/pages/appendix-remoteui.md

Escape color values to prevent sending invalid protocol data.
Fixes: #679

Fix remote ui invalid data

---

sources/Adapters/adv/audio/advAudioDriver.cpp
sources/Services/Midi/MidiService.cpp
sources/Services/Midi/MidiService.h

Move midi processing out of ISR

---

.zed/debug.json
.zed/tasks.json

Adding basic config files to support using Zed editor for picoTrackerAdvance development (debugging not yet supported).

Zed editor support

---

sources/Adapters/adv/Core/Inc/sdmmc.h
sources/Adapters/adv/Core/Src/main.c
sources/Adapters/adv/Core/Src/sdmmc.c

@democloid not sure if the sdmmc.c part needs to be done in a different way via cubemx, please change that if thats the case.
Fixes: #740

Show error mesg on advance when sdcard missing

---

sources/Services/Midi/MidiMessage.h
sources/Services/Midi/MidiOutDevice.cpp
sources/Services/Midi/MidiOutDevice.h
sources/Services/Midi/MidiService.h

Need to make sure midi mesg queue is big enough to handle max number of simultaneous midi instruments, cmds and system mesgs.
Fixes: #752

Ensure Midi mesg queue big enough

---

sources/Services/Midi/MidiMessage.h
sources/Services/Midi/MidiOutDevice.cpp
sources/Services/Midi/MidiOutDevice.h
sources/Services/Midi/MidiService.h

need to make sure midi mesg queue is big enough to handle max number of simultaneous midi instruments, cmds and system mesgs

[cherry-pick] ensure Midi mesg queue big enough

---

sources/Adapters/adv/filesystem/advFileSystem.cpp

Fix file filter on Advance

---

sources/Application/Instruments/WavFile.cpp
sources/Application/Instruments/WavHeaderWriter.cpp
sources/Application/Model/Song.cpp
sources/Application/Model/Table.cpp

Correctly parse RIFF header with JUNK chunks
