docs/MANUAL.md, sources/Adapters/picoTracker/filesystem/picoTrackerFileSystem.cpp, sources/Application/Views/ModalDialogs/ImportSampleDialog.cpp, sources/System/FileSystem/FileSystem.h
For now limit the number of files per sub directory in `samplelib` to 25 per sub directory and truncate filenames to 32 characters.
Basic UI is also added to indicate when the limit is reached.
@democloid I think there may also be a memory leak with `ImportSampleDialog` but I need to spend a bit more time debugging it and can do a followup PR if I find that it is the case.
=> Temporarily limit files per subdir, document in Manual

sources/Adapters/picoTracker/filesystem/picoTrackerFileSystem.cpp, sources/Adapters/picoTracker/filesystem/picoTrackerFileSystem.h, sources/Adapters/picoTracker/gui/picoTrackerGUIWindowImp.cpp, sources/Application/Views/InstrumentView.cpp, sources/Application/Views/ModalDialogs/CMakeLists.txt, sources/Application/Views/ModalDialogs/ImportSampleDialog.cpp, sources/Application/Views/ModalDialogs/PagedImportSampleDialog.cpp, sources/Application/Views/ModalDialogs/PagedImportSampleDialog.h, sources/Application/Views/ModalDialogs/SelectProjectDialog.cpp, sources/CMakeLists.txt, sources/System/FileSystem/FileSystem.cpp, sources/System/FileSystem/FileSystem.h
This signficantly reduces the ram usage when using the import dialog to browse and import samples from the sdcard.
It changes the Import Dialog when built for picotracker to use a new `picoTrackerPagedDir` class that implements a new interface instead of `I_Dir`.  This changes the file system operations to be done in "pages" of files and only stores the indexes of file and subdirectory entries of the currently open directory and only fetches the names of entries on demand in "pages" limited in size to what the dialog UI can display at one time (currently 15).
The `ImportSampleDialog` is also heavily rewritten to make use of the interface and use as little ram as possible.
This doesn't impose any hard limits on the number of files per directory, but it does set initial sizes of max of `96` …
=> Paged file browser

sources/Application/Player/Player.cpp
Transposing using phrase transposition might cause the application to crash Replace the assertion with a log print
from djdiskmachine/LittleGPTracker/pull/5
=> Replace assertion error with log print

sources/CMakeLists.txt
Some boards with the current PCB design seem to have an issue identified by other rp2040 users making custom PCBs with XOSC taking longer than expected to stabilise on boot.
This was verified as fixing the issue of the boards not booting after power cycle post flashing on 3 different boards, from 2 different manufacturing batches.
See this issue for more details: https://github.com/raspberrypi/pico-sdk/pull/457
=> Workaround for some boards that need longer to init clock

sources/Application/Views/InstrumentView.cpp
This should limit the number of characters displayed for the Sample name on the InstrumentView screen to 19 characters (looks about right)..
Related to https://github.com/democloid/picoTracker/issues/63
=> Limit sample name length to 19 characters

sources/Application/Views/PhraseView.cpp
This should limit the name of the instruments on the Phrase view to 15 characters which is the maximum we can view without wrapping.
Related to https://github.com/democloid/picoTracker/issues/88
I don't believe we should remove the space before to give us an extra couple of characters.
=> Limit length of instrument name to 15 characters on Phrase view

sources/Application/Player/Player.cpp, sources/Application/Views/BaseClasses/View.cpp, sources/Application/Views/ChainView.cpp, sources/Application/Views/GrooveView.cpp, sources/Application/Views/PhraseView.cpp, sources/Application/Views/PhraseView.h, sources/Application/Views/SongView.cpp, sources/Application/Views/TableView.cpp, sources/Application/Views/ViewData.h
* Instruments will play when sequencer is stopped
* Play will happen on input of any note or instrument
* Only instruments play, no effects applied.
* Tables and table automation *should* work. Have not tried automation.
* MIDI instruments *should* work, not tested
Code is a bit all over the place and a bit hacky, but probably not too bad. The basic working of this is to start the sequencer every time that we enter a note, but stop the sequencer from advancing and applying effects. Player keeps running indefinitely until we either move away from phrase view, audition another note or start the sequencer in phrase or song view (Play key), as there is not real way to detect that a sound has stopped in any way. This means that any long sample or sound that doesn't end (oscillator loop mode) …
=> Add note audition mode

projects/Makefile, projects/Makefile.OSX, projects/osx_rules, sources/System/Console/Trace.cpp, sources/System/Console/Trace.h
Just to keep testing on alternate platforms, making it a bit nicer to build on OSX (without breaking current picoTracker build)
=> Update building natively on OSX

sources/Application/Instruments/SamplePool.cpp
Shows a status message when importing samples to avoid the delay before it actually starts loading the samples.
Fixes: https://github.com/democloid/picoTracker/issues/40
=> Set status to Importing dir when importing samples

sources/Application/Instruments/SamplePool.cpp
Removes file extension when importing the sample in the simplest way possible.
Fixes: https://github.com/democloid/picoTracker/issues/88
=> Stripping the file extension on Sample Import

.github/workflows/build.yml, sources/Application/Model/BuildNumber.h, sources/Application/Model/Project.h
This sets the build number on each GitHub CI workflow run using the GitHub Actions run number. 
It also uploads the built uf2 binary to make it available after the workflow completes.
Fixes: #100, #50
=> Build number for GitHub CI

sources/Adapters/picoTracker/filesystem/picoTrackerFileSystem.cpp, sources/Adapters/picoTracker/filesystem/picoTrackerFileSystem.h, sources/Adapters/picoTracker/sdcard/sd_card_spi.cpp, sources/CMakeLists.txt
The previous logic to handle file+subdir index listings was incorrect, as it would incorrectly index the file entry indexes list in an attempt to handle paging with a combination of the subdir list and the file list.
Instead of trying to make things work with the 2 separate lists, the code has been simplified to just use a single list for both subdirs and files within a directory by using a struct that holds both an directory entries Filesystem driver index and its type (parent, subdir or file).  I think this is a bit less memory efficient than having the 2 separate lists, but makes the code simpler and more robust.
This also includes a tiny change to tone down the debug logging from the SPI code.
Fixes: #83
=> Fix sample import screen file listing

sources/Adapters/picoTracker/platform/gpio.h, sources/Adapters/picoTracker/system/CMakeLists.txt, sources/Adapters/picoTracker/system/picoTrackerSystem.cpp, sources/Application/AppWindow.cpp, sources/Application/Views/BaseClasses/View.cpp, sources/Application/Views/BaseClasses/View.h, sources/Application/Views/SongView.cpp, sources/CMakeLists.txt
This adds a simple battery gauge display.
For now its only using the previously existing (unused) battery display functionality: so only on the Song screen and only updated every beat only when project is playing back.
The voltage levels used for each "state" of the gauge were determined approximately based on a run down test (timelapse video below).
The intention is to iterate on this in followup PRs to use better mechanism for scheduling reading batt level updates, show gauge on all screens, define a new "CD_ERROR" colour for use when batt level critical and improve the ascii art of the gauge display.
The current state of the gauge UI is:
https://github.com/democloid/picoTracker/assets/71999/67a114db-2435-4ef6-b4e2-bc895244b924
=> Add battery gauge display

docs/MANUAL.md, sources/Application/AppWindow.cpp, sources/Application/AppWindow.h, sources/Application/Model/Config.cpp, sources/Application/Views/BaseClasses/View.cpp, sources/Application/Views/BaseClasses/View.h
This adds 3 new system color definitions: INFO, WARN and ERROR.
It makes use of the new colors for drawing the battery gauge at different states of discharge.
These colors can also be set to values other than the default hardcoded values with in config.xml and the example `config.xml` in the Manual has been updated.
This also exposes to 2 colors "CURSOR" and "CONSOLE" that were previously defined in the code but not documented in the manual and not exposed for user configuration via config.xml though it seems that these are not used as per their naming, eg. the CURSOR color is not actually used for drawing the cursor at the moment.
Note: this is currently stacked on the main loop timer PR branch.
Fixes: #128
=> Add colours

sources/Adapters/picoTracker/filesystem/picoTrackerFileSystem.cpp, sources/Adapters/picoTracker/filesystem/picoTrackerFileSystem.h, sources/Adapters/picoTracker/utils/CMakeLists.txt, sources/Adapters/picoTracker/utils/stringutils.cpp, sources/Adapters/picoTracker/utils/stringutils.h, sources/Application/Instruments/SamplePool.cpp, sources/Application/Instruments/SamplePool.h, sources/Application/Views/ModalDialogs/CMakeLists.txt, sources/Application/Views/ModalDialogs/PagedImportSampleDialog.cpp, sources/System/FileSystem/FileSystem.h
This adds a "statusbar" at the bottom of the sample import screen that shows the size of the currently selected file and the total remaining space in Flash storage for the current project, formated to B, KB or MB.
The free amount will update as samples are imported into the project.
Also there could probably be a bit of tidy up in `picoTrackerPagedDir` to factor out opening a dir into a separate private method as this code has now been copy/pasted a couple of times into diff places in the class.
Note during testing this uncovered an existing bug where some file list entries are incorrectly being assigned the "parent dir" type, but that will be fixed in a separate PR.
Fixes: #132
=> Show flash usage

.github/workflows/build.yml
Update pico sdk release again. This time CI updated to gcc 13.2 to hopefully catch any future regressions on the pico sdk submodule version.
=> Pico sdk version update

sources/Application/Instruments/WavFile.cpp
While evaluating how the LoadInFlash func works, I realized we haven't set this function to work from RAM. While I haven't seen problems related to this, and presumably this works well right now because it may be in XIP cache, this should be explicitly in RAM. This adds 688 bytes of RAM usage.
=> Make LoadInFlash func not be in flash for added safety

sources/Adapters/picoTracker/gui/picoTrackerEventManager.cpp, sources/Adapters/picoTracker/gui/picoTrackerGUIWindowImp.cpp, sources/Adapters/picoTracker/system/picoTrackerEventQueue.cpp, sources/Adapters/picoTracker/system/picoTrackerEventQueue.h
There are moments where the event queue can be starved with the same event and cause problems. This changes the implementation to only add events that are not currently in the queue.
=> Better event queue

sources/Application/Instruments/SampleInstrument.cpp, sources/Application/Instruments/SampleInstrument.h
@maks I had a sense that this could be done, but it was suspiciously easy. Please check this in detail in case I missed anything, but seems to work fine and makes sense because this just stores the data for each track of the last instrument using it, whereas before each instrument was savings it's own data for each track where it might have played, even if that state is not really needed once another instrument triggered on the same track.
=> static RenderParams. Saves 43Kb memory

.devcontainer/devcontainer.json
This makes it easy for someone who is already using devcontainers or who installs a tool that makes them easy to use (eg. VSCode) to get the required tools using the prebuilt docker container (https://github.com/maks/rp2040-devcontainer) I have made, but at the cost of approx 3.8 GB container image. This is especially true for anyone not already using a Ubuntu or Debian based Linux OS, where the instructions from the Pico SDK docs wouldn't work.
For now its only the gcc arm compiler, cmake and other prerequites specified by the Pico C SDK docs but I plan to also add OpenOCD to the image as well.
Also I plan to look at making the image *much* smaller in the future by switching to slimmer version of a base OS image.
=> add dev container config

sources/Application/Model/BuildNumber.h, sources/Application/Model/Project.h, sources/CMakeLists.txt
Updates the defines in the project to be surrounded by #ifndef statements so existing functionality should not be changed.
Updates the CMakeLists.txt file to accept the following flags from the command line when doing a cmake on the project...
-DPROJECT_NUMBER
-DPROJECT_RELEASE
-DBUILD_COUNT
Also with the appropriate defaults that already exist in the existing files.
I'm not sure how these values are updated (are they updated manually or during a pipline build?) if so it would probably be best to remove the defaults from the source code an rely on the config in the CMakeList.txt file. (If this pull request is accepted in the first place :)
=> Enable the PROJECT_NUMBER, PROJECT_RELEASE and BUILD_COUNT to be overridden when running cmake

sources/Application/Model/Config.cpp, sources/Foundation/Variables/Variable.cpp
The previous attempt to store char list variables with their integer IDs was a bit too simplistic as the GetString() method is of course also used to access the actual displayed values for the variables.
This fix the issue by instead having Config explicitly use the GetInt() method and then itself convert the int to a string for xml storage. 
Fixes: #226
=> fix display of char_list variable fields

sources/Application/Instruments/SIDInstrument.cpp, sources/Application/Views/InstrumentView.cpp, sources/Application/Views/InstrumentView.h
ie. moving the cursor through instrument fields causes redraw and the name field is not redrawn because the ram where the string for is has been overwritten.
=> Fix SID instrument naming not displayed after the first redraw

sources/Adapters/picoTracker/system/CMakeLists.txt, sources/Adapters/picoTracker/system/picoTrackerSystem.cpp, sources/Adapters/picoTracker/system/picoTrackerSystem.h, sources/Application/Views/DeviceView.cpp, sources/System/System/System.h
Displays unique ID (from SPI Flash as RP2040 doesnt have its own unique id) on device screen:
=> display unique device ID on device screen

sources/System/Console/Trace.cpp
this prevents crash as we dont check otherwise if stdio uart is enabled.
=> use putchar instead of raw uart access

sources/Adapters/picoTracker/display/mode0.c, sources/Adapters/picoTracker/display/mode0.h, sources/Adapters/picoTracker/system/CMakeLists.txt, sources/Adapters/picoTracker/system/critical_error_message.c, sources/Adapters/picoTracker/system/critical_error_message.h, sources/Adapters/picoTracker/system/picoTrackerSystem.cpp, sources/Application/Model/Config.cpp, sources/Application/Model/Config.h, sources/System/FileSystem/PicoFileSystem.cpp, sources/System/FileSystem/PicoFileSystem.h
Checks for a sdcard early in boot process by changing to root directory and on error displays a error message on screen.
Also improves error handling in some file system functions to allow for adding code in the future for detecting sdcard removal after boot.
Fixes: #124
=> Detect missing sdcard

sources/Adapters/picoTracker/usb/CMakeLists.txt, sources/Adapters/picoTracker/usb/usb_descriptors.c
Custom USB descriptors, using unique SPI Flash ID for serial number:
=> Use our own usb descriptors

sources/Application/Views/InstrumentView.cpp, sources/Application/Views/ModalDialogs/MessageBox.cpp, sources/Application/Views/ModalDialogs/MessageBox.h
This allows us to fix the text overflow in the instrument change confirmation dialog.
Unfort the screenshow below is missing the coloured outline of the Messagebox due to current bug in the remote UI protocol which doesn't send background coloured font char cells.
Fixes: #247
=> Support 2 mesg lines for MessageBox dialogs

.github/workflows/firebase-hosting-merge.yml
GH deploy action was only for `main` branch whereas we still use `master`.
=> Fix branch name for user manual deploy action

sources/Application/Views/InstrumentView.cpp, sources/Application/Views/InstrumentView.h
This improves the current clunky UX by only prompting user with confirmation dialog when an instruments settings have been modified. This implementation is very basic as it doesn't take into account an instrument with settings that were modified in a previous session or where the user modified a instrument setting and set it back to the default value, but its already a big improvement over the current UX.
Fixes: #248
=> Only show instrument type change dialog when instrument modified

sources/Adapters/picoTracker/display/ili9341.c, sources/Adapters/picoTracker/gui/CMakeLists.txt, sources/Adapters/picoTracker/gui/picoRemoteUI.cpp, sources/Adapters/picoTracker/gui/picoRemoteUI.h, sources/Adapters/picoTracker/gui/picoTrackerEventManager.cpp, sources/Adapters/picoTracker/gui/picoTrackerGUIWindowImp.cpp, sources/Adapters/picoTracker/gui/picoTrackerGUIWindowImp.h, sources/Adapters/picoTracker/system/picoTrackerEventQueue.h, sources/Application/AppWindow.cpp, sources/Application/AppWindow.h, sources/Application/Views/DeviceView.cpp, sources/UIFramework/SimpleBaseClasses/GUIWindow.cpp, sources/UIFramework/SimpleBaseClasses/GUIWindow.h, usermanual/content/pages/appendix-remoteui.md
This enhances (with breaking changes) the remote UI protocol to:
* send actual colour values (instead of palette index) to allow clients to show the colour that matches on pT device
* sending current font setting
* receive input events. For now the one event implemented is request for a full screen refresh (inc sending current font)
As part of the changes, the number for the protocol commands changed to improve consistency and allow for future expansion without breaking changes.
Documentation of the remote UI protocol was also added to the user manual as an appendix.
As part of the change to allow clients to request a screen data refresh, the internal pT events for refresh vs flush were separated and related code cleaned up (commented out code removed).
In addition to the protocol …
=> Enhance remote UI protocol

sources/Application/Views/BaseClasses/UISwatchField.cpp
No need to use hash chars now I know how inverted background with space chars works, so this looks a bit nicer.
Fixes: #279
=> Nicer color swatch UI

sources/Application/Model/Chain.h
While this uses an extra approx 4kB of ram, it also saves ~100bytes by replacing boolean array with a bitfield.
Fixes: #288
=> Increase chain count

sources/Application/Utils/HelpLegend.h, sources/Application/Views/ImportView.cpp, sources/Application/Views/PhraseView.cpp, sources/Application/Views/TableView.cpp, usermanual/content/pages/commands.md
Fixes the Fx command help legend on Phrase and Table screen to not overlap battery gauge.
Fixes file size display in the sample import browser that broke with the move to the tiny printf lib and also moves it to the bottom line to be out of the way of the battery gauge.
Also while I was in this part of the code, added missing help legend for GOF, fixed GRV legend help and also updated the user manual entries for both.
Fixes: #284
=> Battery gauge obscures existing fields

.gitignore, sources/Adapters/picoTracker/main/CMakeLists.txt, sources/Application/Instruments/OpalInstrument.cpp, sources/CMakeLists.txt, sources/Externals/opal/CMakeLists.txt, sources/Externals/opal/opal.cpp, sources/Externals/opal/opal.h
As part of trying to improve performance for #283 this PR does some basic optimisation for the OPAL audio rendering code. The main optimisation in the OPAL code is removing function calls from the tight loop by creating a new method for generating samples together for a whole buffer and then further removing more function calls by inlining several small functions. At the cost of 200bytes of ram, the constant LUTs are also forced to be in ram all the time.
For a release builds takes rendering time for 1 `Render()` method call at default bpm and default OPAL instrument settings from:
```
Render took: 3838 (0 ts)[268860620]
Render took: 3820 (0 ts)[268860620]
Render took: 3813 (0 ts)[268860620]
Render took: 3764 (0 ts)[268860620]
Render took: 3800 (0 ts)[268860620]
Render took: 3811 (0 …
```
=> Try to optimise OPAL

sources/Application/Views/PhraseView.cpp, sources/Application/Views/PhraseView.h
Note will now only audition while the Enter key is held down.
Also fixes updating the note being auditioned while playing continues if the note is edited in the Phrase UI.
Fixes: #295
=> Fix note auditioning

sources/Application/Views/BaseClasses/UIField.h, sources/Application/Views/BaseClasses/UITempoField.cpp, sources/Application/Views/BaseClasses/UITempoField.h, sources/Application/Views/BaseClasses/View.h, sources/Application/Views/ChainView.cpp, sources/Application/Views/DeviceView.cpp, sources/Application/Views/FieldView.cpp, sources/Application/Views/GrooveView.cpp, sources/Application/Views/ImportView.cpp, sources/Application/Views/InstrumentView.cpp, sources/Application/Views/ModalDialogs/MessageBox.cpp, sources/Application/Views/PhraseView.cpp, sources/Application/Views/ProjectView.cpp, sources/Application/Views/SelectProjectView.cpp, sources/Application/Views/SongView.cpp, sources/Application/Views/TableView.cpp
Just an automated renaming of the consts to match user facing names of each key in the picoTracker user manual.
Fixes: #298
=> Update const names to match picoTracker key names

sources/Application/Instruments/SamplePool.cpp, sources/Application/Persistency/PersistencyService.cpp, sources/Application/Persistency/PersistencyService.h, sources/Application/Views/ProjectView.cpp, sources/System/FileSystem/PicoFileSystem.cpp, sources/System/FileSystem/PicoFileSystem.h
When the user chooses "New" on the project screen, this will clear the project data and samples if a previous "unnamed" project had been saved with any data or samples.
This also means that the previous restriction on not allowing saving a unnamed project has been removed. 
Fixes: #308
=> Clear previous unnamed project when user does "New"

sources/Application/Instruments/SamplePool.cpp, sources/Application/Instruments/WavFile.cpp
*sigh* need this to work around issue after disabling interrupts when importing samples into flash.
Fixes: #325
=> Hacky workaround for timing issue with interrupts

sources/Application/Views/InstrumentView.cpp
This is a problem, we need to check the ETL library for strict bounds, which I thought we had
=> memory corruption due to vector not being cleared before use fixes #354

sources/CMakeLists.txt
This is a follow up to #369 to enable ETL asserts on debug firmware builds.
=> enable ETL debug asserts for debug builds

sources/Application/Persistency/PersistencyService.cpp
Fix renaming untitled projects which was failing due to being unable to delete the autosave file in the new project.
This also fixes deleting the autosave file when the `untitled` project is purged when the user does an explicit "new project" action.
Fixes: #387
=> Error when saving newly renamed untitled project

sources/Application/Model/Project.cpp, sources/Application/Model/Project.h, sources/Application/Player/Player.cpp, sources/Application/Views/ProjectView.cpp, usermanual/content/pages/commands.md
Also constrain out of range values to be within max-min tempo range.
Fixes: #391
=> use consistent values for min. max, default tempo

sources/Application/Views/ViewData.cpp, usermanual/content/pages/introduction.md
Fixes to use the correct constant for limiting the phrase count when incrementing on the chain screen.
Also sneaks in update to user manual to reflect the new limit on number of chains supported in v2.
Fixes: #329
=> Fix phrase out of range

sources/Application/Instruments/InstrumentBank.cpp
The problem here was that the loop counter was only being incremented for "non empty" instrument slots so if you had non consecutive  non-empty instruments, their correct index into the instruments array (aka their "ID") would be incorrectly saved into the project data file.
Fixes: #368
=> Preserve ID when non-consecutive instrument slots

sources/Application/Views/BaseClasses/UITextField.cpp, sources/Application/Views/BaseClasses/UITextField.h, usermanual/content/pages/projects.md
The UITextField was not using the correct max length constant value for project names, allowing users to enter far too long names and crash.
Also updated the user manual to reflect that the project max length actually used in the code (16) and added documentation on the key for deleting chars in project name.
Fixes: #400
=> Crash when project name too long

sources/Application/AppWindow.cpp, sources/Application/AppWindow.h, sources/Application/Views/BaseClasses/CMakeLists.txt, sources/Application/Views/BaseClasses/UITextField.h, sources/Application/Views/BaseClasses/UITextField.ipp, sources/Application/Views/BaseClasses/stringutils.cpp, sources/Application/Views/BaseClasses/stringutils.h, sources/Application/Views/ProjectView.cpp, sources/Application/Views/ProjectView.h, sources/Foundation/Variables/Variable.cpp, sources/Foundation/Variables/Variable.h
This removes the implicit hardcoded use of UITextField for only project name, allowing it to be used in the future anywhere a textfield widget is required.
The wrinkle here why this ended up being such a big change is that this required making UITextfield a templated class by templated value (`MaxLength`) based on the max field size to match with how the ETL string class that this used by this class works.
Fixes: #403
=> Generic UITextfield

sources/Application/AppWindow.cpp, sources/Application/AppWindow.h, sources/Application/Instruments/CMakeLists.txt, sources/Application/Instruments/InstrumentBank.cpp, sources/Application/Instruments/MidiInstrument.cpp, sources/Application/Instruments/MidiInstrument.h, sources/Application/Utils/CMakeLists.txt, sources/Application/Utils/stringutils.cpp, sources/Application/Utils/stringutils.h, sources/Application/Views/BaseClasses/CMakeLists.txt, sources/Application/Views/BaseClasses/UITextField.h, sources/Application/Views/BaseClasses/UITextField.ipp, sources/Application/Views/BaseClasses/stringutils.h, sources/Application/Views/InstrumentView.cpp, sources/Application/Views/InstrumentView.h, sources/Application/Views/ProjectView.cpp, sources/Foundation/Types/Types.h, sources/Foundation/Variables/Variable.cpp, sources/Foundation/Variables/Variable.h
This adds a `name` field to MIDI instruments to help distinguishing between MIDI instruments once multiple MIDI instruments are created and especially when multiple instruments are created for the same  MIDI channel.
This is a much bigger PR because apart from the above, this also needed to fix ram usage of Variables after previous PR caused ram usage to grow dramatically because it replaced use of `std:string` dynamic mem alloc with static allow of etl:string **but** this meant that all `Variable` objects now had a 40 byte etl:string field while only a tiny minority objects that actually were of "type" `STRING` needed them. The correct solution to this is to actually subtype or template `Variable` class but that can be done in future PR.
Finally `UITextField` was improved to only use …
=> Named midi instruments

sources/Adapters/picoTracker/main/picoTrackerMain.cpp, sources/CMakeLists.txt, sources/System/Console/Trace.cpp, sources/System/Console/Trace.h, sources/config/etl_profile.h
This enables ETL logging to Trace for debug builds. Also, fixes a bug where etl_profile.h wasn't actually getting included by ETL (and thus, was having no actual effect on ETL's behavior).
Basically, ETL does
#include "etl_profile.h"
So the `config` path needs to be on the list of top level include directories.
I'm not great at CMake so I'm not sure if this is the right way to do that.
Closes #443
=> ETL Logging

usermanual/content/pages/songs.md
Minor correction for user manual pertaining to SONG/LIVE modes.
=> SONG/LIVE is toggled with EDIT not ENTER

.github/workflows/build.yml, sources/Adapters/picoTracker/main/picoTrackerMain.cpp, sources/Application/Views/DeviceView.cpp, sources/Application/Views/FieldView.cpp, sources/Application/Views/FieldView.h, sources/Application/Views/InstrumentView.cpp, sources/Application/Views/ProjectView.cpp, sources/Externals/SdFat/src/common/ArduinoFiles.h, sources/Externals/opal/CMakeLists.txt, sources/Foundation/T_Factory.h
This fixes the build for GCC13 and GCC14.
It also updates CI GH Action to use GCC13.2 and potentially could be updated to GCC14.1 as well.
Fixes: #293, #179
=> fixes to build using GCC13

sources/Adapters/picoTracker/audio/audio_i2s.pio
I believe this PR takes care of https://github.com/xiphonics/picoTracker/issues/435 as it gets rid of the clicking sounds I hear on my machine.
I've tested it with HP Low, HP High, and Line Level output levels, and the volume adjustment code appears to still work. This is what I'd expect because I did not move any PIO instructions around or change the loop counter sets
The i2s audio code as written was not correctly sign-extending twos-complement values, because it was padding with zeroes between the MSB and the rest of the value regardless of the MSB value. The correct way to sign extend is to pad with 1s for a negative number and 0s for a positive (i.e. replicate the sign bit)
However, thankfully, the code was inadvertently sign-extending anyway because the data pins for `set` were not …
=> i2s: sign extend correctly; insert 1-bit padding to prevent DAC automute

sources/Adapters/picoTracker/system/picoTrackerEventQueue.cpp, sources/Adapters/picoTracker/system/picoTrackerEventQueue.h
Because both the 1khz timer ISR & the mainloop modify the event queue.
One thing to note is that as a part of this change I removed the deduplication of events being added to the queue for which I don't think there is any reason as far as I know.
All credit for finding and correctly debugging this issue goes to @faithanalog who provided a excellent detailed analysis in #450 🙏🏻 
Fixes: #332, #450
=> use ETL atomic queue to prevent race with ISR

sources/Services/Midi/MidiInDevice.cpp, sources/Services/Midi/MidiInDevice.h
Removing unused per channel midi message handling code saves ~45kB of static ram allocation that was previously introduced when MIDI input handling was recently added.
Fixes: #467
=> Remove unused midi-in handling code to save ram

sources/Foundation/Variables/Variable.cpp
addresses issue #415 
Variable SetString will potentially falsely match strings of the same length if all chars except for the last match.
This allows VFW1 '---N' to be loaded as '----'. 'N' and '-' are detected as not equals and then we detect that we are at the end of s and d. Incrementing s and d during the equality check causes the last char in the string to be ignored.
I tested this loading an existing project which had the ---N value for VFW1.
=> fix SID Waveform not persisting if noise waveform selected

sources/Application/Views/InstrumentView.cpp
Addresses issue #440
Switched the code to use `GetFocus()` to determine the field and access the Variable/VariableID since `FindVariable()` will return for any instrument that doesn't have a `SampleInstrumentTable` variable.
This also supports clearing the Midi Instrument Table field now.
Tested saving and loading a project to make sure the table value persists and can be cleared without crashing. Also tested ENTER+EDIT on OPAL and SID instrument fields to verify the crash no longer occurs on the last field.
=> switched to using GetFocus to find the Table Variable

sources/Adapters/picoTracker/gui/picoTrackerEventManager.cpp, sources/Adapters/picoTracker/gui/picoTrackerEventManager.h
Addresses issue [#337](https://github.com/xiphonics/picoTracker/issues/337)
40ms seemed like a safe number when testing!
Also, I couldn't get clang to check for linting/standard, so apologies if the workflow fails...
=> Add key input debouncing

sources/Application/Views/FieldView.cpp
Multi-column views such as OPAL had the frustrating characteristic that pressing up or down would reset the column to the leftmost column in the grid. This code makes the focus shifting logic column-aware when navigating up or down, snapping to the column with the most-similar X value in the next selected row.
This produces perfect results when navigating columns where the X values match, and decent results when moving between grids with different numbers of columns on a single FieldView.
See https://github.com/xiphonics/picoTracker/issues/491
=> Preserve column when navigating up/down in grid-layout FieldViews

sources/Adapters/picoTracker/audio/audio_i2s.pio
Reverting previous fix for clicks on audio playback (during silences) and stops as this causes a much louder popping when turning off a picoTracker.
This revert is specifically for the stable branch, a separate PR will be done for master branch.
In the future we instead may try to have a fix for clicks that is less intrusive but will also likely only be effective for clicks due to silences during sequencer playback but not when it ends.
Fixes: #484
=> Revert i2s click fix

sources/Adapters/picoTracker/gui/picoTrackerEventManager.cpp
This was discussed in the thread on https://github.com/xiphonics/picoTracker/pull/481 but not implemented with that PR. The summary of the rationale is:
- keep debounce time to a minimum to keep input as responsive as possible
- use a known-good value with a known-good debounce strategy, implementing the default QMK algorithm, which is widely used by many products
This aims to correctly implement the behavior described for debounce algorithm `sym_defer_g` as detailed on https://docs.qmk.fm/feature_debounce_type
> Debouncing per keyboard. On any state change, a global timer is set. When DEBOUNCE milliseconds of no changes has occurred, all input changes are pushed. This is the highest performance algorithm with lowest memory usage and is noise-resistant. 
This is subtly different from the …
=> Use qmk-style debouncing, reduce debounce time to 10ms

sources/Application/AppWindow.cpp, sources/Application/AppWindow.h, sources/Application/Model/Config.cpp, sources/Application/Model/Config.h, sources/Application/Views/BaseClasses/View.h, sources/Application/Views/DeviceView.cpp, sources/Application/Views/DeviceView.h, sources/Application/Views/SongView.cpp, sources/Foundation/Types/Types.h
There is not enough room for all the new UI colour fields in Device screen so for now most not yet added to the UI and only the SongViewFE and SongView00 colours are added for demonsation purposes.
This can be considered part one of this work and a subsequent PR will add a new screen for "theme" settings where all the colour fields and the font setting field will be moved into which will be accessed via a button on the Device screen.
This partially addresses #181.
=> More UI colours to match those in latest LGPT

sources/Application/Mixer/MixerService.cpp, sources/Application/Views/ProjectView.cpp
This limits the master volume to now be a maxium of unity gain (0dB), displays as a percentage, allows to go down to 0% and changes the label slightly to read `master vol:`
Fixes: #453
=> Use log scale for master vol, allow max of 0dB

sources/Application/Audio/AudioFileStreamer.cpp, sources/Application/Model/Project.cpp, sources/Application/Model/Project.h, sources/Application/Views/ImportView.cpp, sources/Application/Views/ImportView.h, sources/Application/Views/ProjectView.cpp, sources/Foundation/Types/Types.h, usermanual/content/pages/instruments.md, usermanual/content/pages/keypadcombos.md
This provides for a separate volume setting for sample preview volume and provides a UI for adjusting it on the import screen using `ENTER+UP/DOWN`
Fixes: #487
=> Separate preview volume

sources/Application/Views/InstrumentView.cpp, sources/Application/Views/InstrumentView.h, sources/Foundation/Variables/Variable.cpp, sources/Foundation/Variables/Variable.h
This fixes the check that happens before an instrument type change by the user is attempted to see if the instrument has been modified, because if it has the user is first prompted to confirm the change and potentially lose changes.
Also fixes a bug which was changing the instrument type name field even if the user didn't confirm the instrument type change.
Finally we also have the functionality in place now to reset instruments back to default settings if we choose to have a keycombo for this in the future.
Fixes: #458
=> Fix check for modified instruments

sources/Adapters/picoTracker/gui/picoTrackerEventManager.cpp, sources/Application/AppWindow.cpp, sources/Application/Player/PlayerMixer.cpp, sources/Application/Views/BaseClasses/View.cpp, sources/Application/Views/BaseClasses/View.h, sources/Application/Views/MixerView.cpp, sources/Application/Views/MixerView.h, sources/Services/Audio/AudioMixer.cpp, sources/UIFramework/SimpleBaseClasses/EventManager.h
This improves performance of vumeter drawing up to a point as without vsync we can't really prevent tearing.
It also fixes vumeters to updated when the sequencer is not running for example with midi input or possible other reasons that may be introduced in the future.
This also add "inertia" to the vumeters, giving a pleasing "slower fall off" when volume levels drop suddenly (eg. when playback stops).
Fixes: #454
=> Optimise drawing vu meters

sources/Application/Instruments/I_Instrument.cpp, sources/Application/Persistency/PersistencyService.cpp, sources/Application/Views/InstrumentImportView.cpp, sources/Application/Views/InstrumentView.cpp
Fixes handling import/export action field event handling.
This also fixes regression that occurred in a prev change to add firmware version property that ended up creating a new seond top-level element.  Instead we fix here to just add that prop to the instrument element that already gets created by I_Instrument::SaveContent()
NOTE: this is stacked on prev PR as it relies on changes made there for dialog callback functions being std::function.
Fixes: #556
=> Fix instrument import, export regressions

sources/Application/Instruments/SampleInstrument.cpp, sources/Application/Views/InstrumentView.cpp
This also changes previous behaviour to now apply the start and end points to create the "effective" part of the sample that is sliced when slices are used.
**Note:** It can be difficult to test this PR as  you need to be aware that #567 at the moment causes fields to not correctly update when moving to/from the phrase screen on projects with more than 1 instrument.
Fixes: #556
=> Fix sample start and end points

sources/Adapters/picoTracker/midi/picoTrackerUSBMidiInDevice.cpp, sources/Application/Instruments/OpalInstrument.cpp, sources/Application/Instruments/SampleInstrument.cpp, sources/Application/Player/PlayerChannel.cpp, sources/Application/Views/ConsoleView.h, sources/Services/Midi/CMakeLists.txt, sources/Services/Midi/MidiInDevice.cpp, sources/Services/Midi/MidiInDevice.h, sources/Services/Midi/MidiNoteTracker.cpp, sources/Services/Midi/MidiNoteTracker.h, usermanual/content/pages/midi.md
Apart from fixing MIDI note input this also cleans up code for correctly handling sampler instrument stops and adds MIDI In documentation which documents the limitation that unlike sampler instruments, synth instruments are not polyphonic with MIDI input.
Also includes some code cleanup to make format linter and compiler (for release mode) happy.
Fixes: #508 , #580
=> Fix handling multiple MIDI IN notes

sources/Services/Midi/MidiInDevice.cpp, sources/Services/Midi/MidiInDevice.h
Tested with input with:
Chromatone MIDI webmidi router over USB
Novation Launchpad Mk3 over USB
picoTracker over TRS
TE EP-133 over TRS
Fixes: https://github.com/xiphonics/picoTracker/issues/546
=> Fix MIDI input transport-messages

sources/Application/Views/BaseClasses/View.cpp, sources/Application/Views/BaseClasses/View.h, sources/Application/Views/PhraseView.cpp
This was missed in the previous fix for #576 that only fixed the table screen.
Fixes: #576
=> Fix vu meter to not overlap grid on phrase screen

sources/Application/Model/Config.cpp, sources/Application/Model/Config.h, sources/Application/Model/ThemeConstants.h, sources/Application/Views/ThemeView.cpp, sources/Application/Views/ThemeView.h, sources/Foundation/Types/Types.h
In fixing the theme export UI to work I made it consistent with instrument name and project name UI in other screens.
While fixing this I also found bug in the config.xml handling that could cause the parameters to be written out to xml twice and in general cleaned up the config xml parsing to require *almost* none of the special case per variable code that was previously being used.
Fixes: #586
=> Theme export broken

sources/Application/Model/Project.cpp, sources/Application/Model/Project.h
The variable seems to have some how been lost, like in a previous merge.
Also use define for all default volumes.
Fixes: #611
=> Fix preview volume

sources/Application/Player/Player.cpp
This was found while investigating #592 but does not fix it rather fixes related issue where DLY when in 2nd slot was incorrectly using value of first slot.
=> Fix DLY value when used as 2nd command

sources/Application/Instruments/SampleInstrument.cpp, sources/Application/Instruments/SampleInstrument.h, sources/Application/Instruments/WavFile.cpp, sources/Application/Instruments/WavFile.h, sources/Application/Views/InstrumentView.cpp, sources/Application/Views/InstrumentView.h, sources/Foundation/Types/Types.h
This reverts previous commits that added slices functionality.
=> Revert slices

sources/Adapters/adv/filesystem/picoFileSystem.cpp, sources/Adapters/adv/system/advSamplePool.cpp, sources/Application/Views/ImportView.cpp
Also fixes hardfault which occurred due to missing 4 byte alignment of writes in to sample pool external ram.
=> fix parent dir handling in advance filesystem

sources/Adapters/adv/filesystem/CMakeLists.txt, sources/Adapters/adv/filesystem/advFileSystem.cpp, sources/Adapters/adv/filesystem/advFileSystem.h, sources/Adapters/adv/gui/advGUIWindowImp.cpp, sources/Adapters/adv/system/advSystem.cpp, sources/Adapters/picoTracker/filesystem/picoTrackerFileSystem.cpp, sources/Adapters/picoTracker/filesystem/picoTrackerFileSystem.h, sources/System/FileSystem/I_File.h
Cleans up old commented out code in advance filesystem, renames the class to match convention and implements missing isParentRoot().
Also removes unused duplicate DeleteFile() function on I_file as its already provided by the FileSystem interface class.
Fixes: #733
=> Cleanup adv Filesystem code

.zed/debug.json, .zed/tasks.json, sources/Adapters/adv/audio/advAudioDriver.cpp, sources/Adapters/adv/audio/record.cpp, sources/Adapters/adv/audio/record.h, sources/Adapters/adv/filesystem/CMakeLists.txt, sources/Adapters/adv/filesystem/advFileSystem.cpp, sources/Adapters/adv/filesystem/advFileSystem.h, sources/Adapters/adv/gui/SerialDebugUI.cpp, sources/Adapters/adv/gui/advEventManager.cpp, sources/Adapters/adv/gui/advGUIWindowImp.cpp, sources/Adapters/adv/midi/advMidiOutDevice.cpp, sources/Adapters/adv/system/advSamplePool.cpp, sources/Adapters/adv/system/advSamplePool.h, sources/Adapters/adv/system/advSystem.cpp, sources/Adapters/picoTracker/filesystem/picoTrackerFileSystem.cpp, sources/Adapters/picoTracker/filesystem/picoTrackerFileSystem.h, sources/Application/AppWindow.h, sources/Application/Instruments/CMakeLists.txt, sources/Application/Instruments/WavFileWriter.cpp, sources/Application/Instruments/WavHeaderWriter.cpp, sources/Application/Instruments/WavHeaderWriter.h, sources/Application/Views/ImportView.cpp, sources/CMakeLists.txt, sources/Services/Midi/MidiService.cpp, sources/Services/Midi/MidiService.h, sources/System/FileSystem/I_File.h, sources/UIFramework/SimpleBaseClasses/EventManager.h
This refactors existing wave header code out on `WaveFileWriter` into a separate utility class that can then be used by both the `WaveFileWriter` and by `record.cpp`.
Fixes: #717
=> Record to files with wav header

sources/Application/Instruments/MidiInstrument.cpp
Comments out verbose debug logging to prevent audio overruns when testing with debug builds playing large numbers of concurrent MIDI notes.
=> Tone down logging for midi note playback

sources/Application/Player/Player.cpp
OnPlayerStop() needs to be called to have rendered wav files be closed.
This was working "by accident" with larger renders as they would get the file buffer mostly flushed out even without the file being properly closed.
=> Add missed fn call to properly close render files

sources/Application/Views/ImportView.cpp, sources/Application/Views/ImportView.h
This adds import and edit onscreen buttons for the sample import file browser.
Note that this is the first in a series of PRs that will lead to completing #637
The next PR will complete the sample editor functionality.
Fixes: #790
=> import, edit onscreen buttons for file browser

sources/Application/Views/SongView.cpp
Note: the key combo is still considered a temp placeholder for nav'ing to the record screen.
=> Dont start playback when nav'ing to rec screen

sources/Adapters/adv/audio/advAudioDriver.cpp
This is a problem in preemptive multitasking. WE are not enabling that right now (or ever?) but this is the right way to do it anyways.
=> Semaphore for Advance audio driver created in wrong order

sources/Adapters/picoTracker/system/picoTrackerSystem.cpp, sources/Adapters/picoTracker/system/picoTrackerSystem.h, sources/Application/Application.cpp
Fixes advance not applying brightness from config on boot.
Fixes: #835
=> Apply brightness onboot in xplatform way
